routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;


Route::get('login', [LoginController::class, 'redirectToProvider'])->name('login');
Route::get('login/callback', [LoginController::class, 'handleProviderCallback']);


Route::middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return view('pages.home.index');
    })->name('home');


    Route::resources([
        'advertisers' => \App\Http\Controllers\AdvertiserController::class,
        'advertisers.campaigns' => \App\Http\Controllers\CampaignController::class,
        'advertisers.campaigns.banners' => \App\Http\Controllers\BannerController::class,
        'websites' => \App\Http\Controllers\WebsiteController::class,
        'websites.pages' => \App\Http\Controllers\PageController::class,
        'websites.zones' => \App\Http\Controllers\ZoneController::class,
        'rectangles' => \App\Http\Controllers\RectangleController::class,
    ]);

    Route::get('pages', [\App\Http\Controllers\PageController::class, 'index'])->name('pages.index');
    Route::get('zones', [\App\Http\Controllers\ZoneController::class, 'index'])->name('zones.index');

    Route::get('campaigns', [\App\Http\Controllers\CampaignController::class, 'index'])
        ->name('campaigns.index');

    Route::get('banners', [\App\Http\Controllers\BannerController::class, 'index'])
        ->name('banners.index');

    Route::delete('banners/{banner}', [\App\Http\Controllers\BannerController::class, 'destroy'])
        ->name('banners.delete');


    Route::get('banners/{banner}', [\App\Http\Controllers\BannerController::class, 'implicit'])
        ->name('banners.show');


    Route::get('advertisers/{advertiser}/banners', [\App\Http\Controllers\BannerController::class, 'index'])
        ->name('advertisers.banners.index');


    Route::get('advertisers/{advertiser}/banners/{campaign}/clone/{banner}', [\App\Http\Controllers\BannerController::class, 'clone'])
        ->name('advertisers.banners.clone');

});


Route::get('fetch', [\App\Http\Controllers\FetchController::class, 'index']);

app/Models/Advertiser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Advertiser extends Model
{
    use HasFactory;


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function campaigns()
    {
        return $this->hasMany(Campaign::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
     */
    public function banners()
    {
        return $this->hasManyThrough(Banner::class , Campaign::class);
    }
}

app/Http/Controllers/AdvertiserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreAdvertiser;
use App\Http\Requests\UpdateAdvertiser;
use App\Models\Advertiser;

class AdvertiserController extends Controller
{

    public function index()
    {
        $collection = Advertiser::all();
        return view('pages.advertiser.index' , compact('collection'));
    }

    public function create()
    {
        $advertiser = new Advertiser();
        return view('pages.advertiser.createOrUpdate' , compact('advertiser'));
    }


    public function store(StoreAdvertiser $request)
    {

        $advertiser = new Advertiser();
        $advertiser->name = $request->get('name');
        $advertiser->contact = $request->get('contact');
        $advertiser->email = $request->get('email');
        $advertiser->save();

        return redirect()->route('advertisers.index');
    }

    public function show(Advertiser $advertiser)
    {
        return redirect()->route('advertisers.edit' , [$advertiser->id]);
    }

    public function edit(Advertiser $advertiser)
    {
        return view('pages.advertiser.createOrUpdate' , compact('advertiser'));
    }


    public function update(UpdateAdvertiser $request, Advertiser $advertiser)
    {
        $advertiser->name = $request->get('name');
        $advertiser->contact = $request->get('contact');
        $advertiser->email = $request->get('email');
        $advertiser->save();
        return redirect()->route('advertisers.index');
    }

    public function destroy(Advertiser $advertiser)
    {
        $advertiser->delete();
        return redirect()->route('advertisers.index');
    }
}

resources/views/pages/advertiser/createOrUpdate.blade.php
@extends('layouts.app')

@section('message')
    @if ($errors->any())
        <div class="alert alert-primary alert-dismissible">
            @php
              $class = 'alert alert-danger';
            @endphp

            @foreach($errors->all() as $error)

                @if ($loop->last)
                    @php
                    $class .= ' mb-0';
                    @endphp
                @endif
                <div class="{{ $class }}" role="alert">
                    {{ $error }}
                </div>
            @endforeach
        </div>
    @endif

@endsection

@section('content')
    @php
        if ($advertiser->id){
            $route = route('advertisers.update' , [$advertiser->id]) ;
            $method='PUT';
            $title = 'Edit';
        } else {
            $route = route('advertisers.store');
            $method='POST';
            $title = 'New';
        }
    @endphp

    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        {{ $title }} Advertiser
                    </h2>

                </div>
                <div class="panel-container show">
                    <div class="panel-content">

                        <form method="POST" action="{{ $route }}">
                            @csrf
                            @method($method)

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label" for="advertiser-name">Name*</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="name"
                                           id="advertiser-name" value="{{ old('name') ?? $advertiser->name }}" >
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label" for="advertiser-contact">Contact</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="contact"
                                           id="advertiser-contact" value="{{ old('contact') ?? $advertiser->contact }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label" for="advertiser-email">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" name="email"
                                           id="advertiser-email" value="{{ old('email') ?? $advertiser->email  }}">
                                </div>
                            </div>

                            <div class="panel-content border-faded border-left-0 border-right-0 border-bottom-0 d-flex flex-row-reverse">
                                <button type="submit" class="btn btn-primary ml-3">Save changes</button>
                                <a type="button" class="btn btn-secondary ml-3" href="javascript:javascript:history.go(-1)">Close</a>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection



@push('page-scripts')
    <script type="text/javascript">


    </script>

@endpush

resources/views/pages/advertiser/index.blade.php
@extends('layouts.app')

@section('content')


    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Advertiser
                    </h2>

                    <div class="panel-toolbar">
                        <a href="{{ route('advertisers.create') }}" type="button" class="btn btn-xs btn-success ml-3">Create new advertiser</a>
                    </div>

                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <table class="table table-sm table-striped">
                            <thead class="bg-fusion-50">
                            <th>
                                Name
                            </th>
                            <th>
                                Contact
                            </th>
                            <th>
                                Email
                            </th>
                            <th></th>
                            </thead>
                            <tbody>
                            @foreach ($collection as $entity)
                                <tr>

                                    <td style="width: 40%;">
                                        <a href="{{ route('advertisers.edit' ,[$entity->id]) }}">
                                            {{ $entity->name }}
                                        </a>

                                    </td>

                                    <td>
                                        {{ $entity->contact }}
                                    </td>

                                    <td>
                                        {{ $entity->email }}
                                    </td>


                                    <td class="text-right">
                                        <a type="button" class="btn btn-primary btn-xs waves-effect waves-themed"
                                           href="{{ route('advertisers.campaigns.create' , [$entity->id]) }}">Add new campaign</a>
                                        <a type="button" class="btn btn-info btn-xs waves-effect waves-themed ml-2"
                                           href="{{ route('advertisers.campaigns.index' , [$entity->id]) }}">Campaigns</a>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection



@push('page-scripts')
    <script type="text/javascript">


    </script>

@endpush