routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;


Route::get('login', [LoginController::class, 'redirectToProvider'])->name('login');
Route::get('login/callback', [LoginController::class, 'handleProviderCallback']);


Route::middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return view('pages.home.index');
    })->name('home');


    Route::resources([
        'advertisers' => \App\Http\Controllers\AdvertiserController::class,
        'advertisers.campaigns' => \App\Http\Controllers\CampaignController::class,
        'advertisers.campaigns.banners' => \App\Http\Controllers\BannerController::class,
        'websites' => \App\Http\Controllers\WebsiteController::class,
        'websites.pages' => \App\Http\Controllers\PageController::class,
        'websites.zones' => \App\Http\Controllers\ZoneController::class,
        'rectangles' => \App\Http\Controllers\RectangleController::class,
    ]);

    Route::get('pages', [\App\Http\Controllers\PageController::class, 'index'])->name('pages.index');
    Route::get('zones', [\App\Http\Controllers\ZoneController::class, 'index'])->name('zones.index');

    Route::get('campaigns', [\App\Http\Controllers\CampaignController::class, 'index'])
        ->name('campaigns.index');

    Route::get('banners', [\App\Http\Controllers\BannerController::class, 'index'])
        ->name('banners.index');

    Route::delete('banners/{banner}', [\App\Http\Controllers\BannerController::class, 'destroy'])
        ->name('banners.delete');


    Route::get('banners/{banner}', [\App\Http\Controllers\BannerController::class, 'implicit'])
        ->name('banners.show');


    Route::get('advertisers/{advertiser}/banners', [\App\Http\Controllers\BannerController::class, 'index'])
        ->name('advertisers.banners.index');


    Route::get('advertisers/{advertiser}/banners/{campaign}/clone/{banner}', [\App\Http\Controllers\BannerController::class, 'clone'])
        ->name('advertisers.banners.clone');

});


Route::get('fetch', [\App\Http\Controllers\FetchController::class, 'index']);

resources/views/layouts/partials/left-aside.blade.php
<aside class="page-sidebar">
    <div class="page-logo">
        <a href="{{ route('home') }}" class="page-logo-link d-flex align-items-center position-relative">
            <img src="{!! asset('smartadmin/img/logo.png') !!}" alt="SmartAdmin WebApp" aria-roledescription="logo">
            <span class="page-logo-text mr-1">Ats</span>
        </a>
    </div>
    <!-- BEGIN PRIMARY NAVIGATION -->
    <nav id="js-primary-nav" class="primary-nav" role="navigation">

        <ul id="js-nav-menu" class="nav-menu">

            <li>
                <a href="{{ route('advertisers.index') }}" title="Advertisers" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Advertisers</span>
                </a>
            </li>

            <li>
                <a href="{{ route('campaigns.index') }}" title="Campaigns" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Campaigns</span>
                </a>
            </li>

            <li>
                <a href="{{ route('banners.index') }}" title="Websites" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Banners</span>
                </a>
            </li>

            <li class="nav-title">Management</li>

            <li>
                <a href="{{ route('websites.index') }}" title="Websites" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Websites</span>
                </a>
            </li>

            <li>
                <a href="{{ route('pages.index') }}" title="Pages" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Pages</span>
                </a>
            </li>

            <li>
                <a href="{{ route('zones.index') }}" title="Zones" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Zones</span>
                </a>
            </li>


            <li class="nav-title">System</li>

            <li>
                <a href="{{ route('rectangles.index') }}" title="Rectangles" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Rectangles</span>
                </a>
            </li>

            <li>
                <a href="/" title="Users" >
                    <i class="fal fa-alien"></i>
                    <span class="nav-link-text" >Users</span>
                </a>
            </li>


        </ul>

    </nav>
    <!-- END PRIMARY NAVIGATION -->

</aside>